name: Darling CI

on: [push, pull_request]

jobs:
  build-deb:
    runs-on: ubuntu-22.04
    steps:
    - name: Free up space
      uses: rokibhasansagar/slimhub_actions@main
    - uses: actions/checkout@v4
      with:
        repository: darlinghq/darling
        fetch-depth: 0

    - name: Checkout submodules
      shell: bash
      run: |
        git submodule update --init --recursive --depth=1

    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install devscripts equivs debhelper
        sudo mk-build-deps -i -r -t "apt-get --no-install-recommends -y" debian/control

    # see https://github.com/actions/virtual-environments/issues/2606#issuecomment-772683150

    - name: Build DEBs
      run: |
        ./tools/debian/make-deb

    - name: Move DEBs
      run: |
        mkdir dist && mv ../*.deb dist

    - name: Upload artifacts
      uses: actions/upload-artifact@v4.1.0
      with:
        name: 'debs'
        path: dist/

  build-dsc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: darlinghq/darling
        fetch-depth: 0

    - name: Checkout submodules
      shell: bash
      run: |
        git submodule update --init --recursive --depth=1

    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install devscripts equivs debhelper

    - name: Build DSCs
      run: |
        ./tools/debian/make-deb --dsc

    - name: Move DSCs
      run: |
        mkdir source && mv ../*~$(lsb_release -cs).* source

    - name: Upload artifacts
      uses: actions/upload-artifact@v4.1.0
      with:
        name: 'source'
        path: source/
